// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kowchqjqdarwzpghefmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvd2NocWpxZGFyd3pwZ2hlZm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzgxNTgsImV4cCI6MjA2NzIxNDE1OH0.5xuq7hCyRg2gnE_hSVkz3g7IKM6LenQ66e2ns1Li9hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});